INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (1, '철거', '20평', 150);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (2, '철거', '30평', 350);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (3, '철거', '40평', 550);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (4, '철거', '50평', 600);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (5, '인건비', '전기', 25);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (6, '인건비', '철거', 25);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (7, '인건비', '타일', 28);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (8, '폐기물', '0.5톤', 20);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (9, '폐기물', '1톤', 40);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (10, '폐기물', '2톤', 50);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (11, '샷시', 'KCC_21평', 570);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (12, '샷시', 'KCC_24평', 650);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (13, '샷시', 'KCC_28평', 700);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (14, '샷시', 'KCC_32평', 780);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (15, '샷시', 'KCC_37평', 950);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (16, '샷시', 'KCC_45평', 1000);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (17, '샷시', 'KCC_48평', 1100);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (18, '샷시', 'LG_21평', 700);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (19, '샷시', 'LG_24평', 810);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (20, '샷시', 'LG_28평', 860);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (21, '샷시', 'LG_32평', 1000);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (22, '샷시', 'LG_37평', 1220);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (23, '샷시', 'LG_45평', 1300);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (24, '샷시', 'LG_48평', 1400);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (25, '샷시', '휴그린_21평', 510);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (26, '샷시', '휴그린_24평', 600);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (27, '샷시', '휴그린_28평', 630);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (28, '샷시', '휴그린_32평', 720);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (29, '샷시', '휴그린_37평', 870);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (30, '샷시', '휴그린_45평', 940);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (31, '샷시', '휴그린_48평', 1000);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (32, '인건비', '조공(전기)', 20);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (33, '인건비', '기공(전기)', 30);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (34, '스위치', '진흥전기_1구', 0.2);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (35, '스위치', '진흥전기_2구', 0.3);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (36, '스위치', '진흥전기_3구', 0.35);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (37, '스위치', '진흥전기_4구', 0.5);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (38, '스위치', '진흥전기_5구', 0.6);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (39, '스위치', '진흥전기_6구', 0.7);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (40, '스위치', '나노전기_1구', 0.25);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (41, '스위치', '나노전기_2구', 0.3);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (42, '스위치', '나노전기_3구', 0.4);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (43, '스위치', '나노전기_4구', 0.63);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (44, '스위치', '나노전기_5구', 0.7);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (45, '스위치', '나노전기_6구', 0.8);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (46, '스위치', '르그랑아펠라_1구', 0.35);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (47, '스위치', '르그랑아펠라_2구', 0.55);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (48, '스위치', '르그랑아펠라_3구', 0.65);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (49, '스위치', '르그랑아펠라_4구', 1);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (50, '스위치', '르그랑아펠라_5구', 1.15);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (51, '스위치', '르그랑아펠라_6구', 1.27);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (52, '스위치', '르그랑아테오_1구', 2.3);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (53, '스위치', '르그랑아테오_2구', 2.8);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (54, '스위치', '르그랑아테오_3구', 3.6);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (55, '스위치', '르그랑아테오_4구', 5.4);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (56, '스위치', '르그랑아테오_5구', 5.9);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (57, '스위치', '르그랑아테오_6구', 6.5);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (58, '스위치', '융_1구', 5.5);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (59, '스위치', '융_2구', 7.25);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (60, '스위치', '융_3구', 10.25);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (61, '스위치', '융_4구', 12.75);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (62, '스위치', '융_5구', 15.25);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (63, '스위치', '융_6구', 18);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (64, '콘센트', '진흥전기_1구', 0.2);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (65, '콘센트', '진흥전기_2구', 0.25);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (66, '콘센트', '진흥전기_4구', 0.46);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (67, '콘센트', '나노전기_1구', 0.25);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (68, '콘센트', '나노전기_2구', 0.37);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (69, '콘센트', '나노전기_4구', 0.5);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (70, '콘센트', '르그랑아펠라_1구', 0.35);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (71, '콘센트', '르그랑아펠라_2구', 0.45);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (72, '콘센트', '르그랑아펠라_4구', 0.75);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (73, '콘센트', '르그랑아테오_1구', 2);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (74, '콘센트', '르그랑아테오_2구', 2.2);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (75, '콘센트', '르그랑아테오_4구', 4);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (76, '콘센트', '융_1구', 5.3);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (77, '콘센트', '융_2구', 10.75);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (78, '콘센트', '융_3구', 15.75);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (79, '콘센트', '융_4구', 21.7);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (80, '콘센트', '융_5구', 27.75);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (81, '콘센트', '진흥전기_1구(방우)', 0.3);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (82, '콘센트', '진흥전기_2구(방우)', 0.35);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (83, '콘센트', '나노전기_1구(방우)', 0.3);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (84, '콘센트', '나노전기_2구(방우)', 0.35);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (85, '콘센트', '나노전기_4구(방우)', 0.8);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (86, '콘센트', '르그랑아펠라_1구(방우)', 0.5);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (87, '콘센트', '르그랑아펠라_2구(방우)', 0.6);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (88, '콘센트', '르그랑아테오_1구(방우)', 0.5);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (89, '콘센트', '르그랑아테오_2구(방우)', 0.6);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (96, '에어컨', '실내기_2대', 350);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (97, '에어컨', '실내기_3대', 450);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (98, '에어컨', '실내기_4대', 550);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (99, '조명', '벽등_직부등', 4);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (100, '조명', '라인조명', 30);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (101, '조명', '간접조명_m당', 0.2);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (102, '조명', '마그네틱트랙_m당', 7);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (103, '조명', '마그네틱조명_개당', 8);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (104, '조명', '매립등_개당', 1.2);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (105, '목공', '히든도어', 300);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (106, '목공', '히든도어_벽체공사', 400);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (109, '목공', '9mm도어', 200);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (110, '목공', '9mm도어_벽체공사', 150);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (114, '목공', '우물천장', 230);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (115, '목공 ', '커튼박스', 20);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (116, '목공', '몰딩공사', 130);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (117, '목공', '천정공사', 150);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (118, '목공', '벽체공사', 100);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (119, '목공', '단열공사', 170);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (120, '인건비', '타일', 25);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (121, '인건비', '타일', 35);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (122, '타일', '300 x 300각_포세린타일', 1.7);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (123, '타일', '300 x 600각_포세린타일', 3.7);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (124, '타일', '600 x 600각_포세린타일', 6);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (125, '타일', '600 x 1200각_포세린타일', 12);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (126, '타일', '1200 x 1200각_포세린타일', 20);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (127, '타일', '300 x 300각_폴리싱타일', 1.7);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (128, '타일', '300 x 600각_폴리싱타일', 3.7);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (129, '타일', '600 x 600각_폴리싱타일', 6);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (130, '타일', '600 x 1200각_폴리싱타일', 12);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (131, '타일', '1200 x 1200각_폴리싱타일', 20);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (132, '타일부자재', '세라픽스(타일본드)_20kg ', 2.7);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (133, '타일부자재', '레미탈_25kg', 0.75);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (134, '타일부자재', '에폭시_20kg', 5.7);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (135, '타일부자재', '드라이픽스(난방용)_ 20kg', 1.5);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (136, '타일부자재', '드라이픽스_20kg', 1.3);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (137, '타일부자재 ', '압착시멘트_20kg', 0.9);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (138, '타일부자재', '메지(줄눈)_2kg', 0.2);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (139, '타일부자재', '아덱스 메지(줄눈)_2kg', 0.8);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (140, '타일부자재', '케라폭시(줄눈)_5kg', 9.5);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (141, '인건비 ', '도기(화장실)_욕실(한칸당)', 22);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (143, '화장실 공사', '대림바스_세면대', 13);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (144, '화장실 공사', '대림바스_양변기', 20);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (145, '화장실 공사', '대림바스_세면수전', 5);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (146, '화장실 공사', '대림바스_샤워수전', 9);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (147, '화장실 공사 ', '대림바스_욕조수전', 15);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (148, '화장실 공사', '대림바스_수건걸이', 2.3);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (149, '화장실 공사 ', '대림바스_휴지걸이', 6);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (151, '화장실 공사', '대림바스_슬라이딩장/욕실장', 15);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (152, '화장실 공사', '대림바스_욕조', 25);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (153, '화장실 공사', '대림바스_샤워기거치대', 6);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (154, '화장실 공사 ', '대림바스_비데', 55);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (155, '화장실 공사', '대림바스_일체형비데 ', 90);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (156, '화장실 공사 ', '크린스_세면대', 10);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (157, '화장실 공사', '크린스_양변기', 15);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (158, '화장실 공사', '크린스_수전', 6);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (159, '화장실 공사 ', '아메리칸 스탠다드_세면대', 16);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (160, '화장실 공사 ', '아메리칸 스탠다드_양변기', 30);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (161, '화장실 공사 ', '아메리칸 스탠다드_세면기 수전', 14);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (162, '화장실 공사 ', '아메리칸 스탠다드_샤워기 수전', 25);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (163, '화장실 공사 ', '아메리칸 스탠다드_욕조 수전', 50);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (164, '화장실 공사', '아메리칸 스탠다드_레인샤워 (해바라기 샤워)', 42);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (165, '화장실 공사 ', '아메리칸 스탠다드_매립수전', 32);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (166, '화장실 공사', '아메리칸 스탠다드_수건걸이', 6.5);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (167, '화장실 공사 ', '아메리칸 스탠다드_휴지걸이', 11);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (168, '화장실 공사', '아메리칸 스탠다드_일체형비데', 100);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (169, '화장실 공사', '아메리칸 스탠다드_비데 ', 25);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (170, '화장실 공사 ', '아메리칸 스탠다드_욕조', 30);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (171, '화장실 공사 ', '아메리칸 스탠다드_악세사리', 7);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (172, '화장실 공사 ', '그로헤_세면기', 28);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (173, '화장실 공사 ', '그로헤_양변기', 50);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (174, '화장실 공사 ', '그로헤_샤워욕조수전', 70);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (175, '화장실 공사', '그로헤_세면기수전', 85);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (176, '화장실 공사 ', '그로헤_싱크수전', 75);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (177, '화장실 공사', '그로헤_매립수전', 45);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (178, '화장실 공사 ', '그로헤_매립욕조수전', 76);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (179, '화장실 공사', '그로헤_수건걸이', 12);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (180, '화장실 공사 ', '그로헤_휴지걸이', 7.5);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (181, '화장실 공사 ', '슬라이드장_욕실장', 25);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (182, '화장실 공사', '이노솔(욕실 천장재)_욕실 한칸', 27);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (183, '화장실 공사', 'SMC(욕실 천장재)_욕실 한칸', 12);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (184, '화장실 공사', '힘펠_환풍기', 7.5);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (185, '화장실 공사 ', '힘펠 휴젠트_환풍기', 40);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (186, '화장실 공사', '하츠_환풍기', 4);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (187, '화장실 공사', '하츠 티오람_환풍기', 30);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (188, '화장실 공사', '욕조', 13);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (189, '화장실 공사', '파티션', 25);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (190, '인건비', '필름 ', 25);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (191, '필름지', 'LG하우시스_1롤', 15);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (192, '필름지 ', '영림_1롤', 15);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (193, '필름지', '예림_1롤', 15);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (194, '필름지', '선우드_1롤', 15);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (195, '필름지', '우딘 _1롤', 15);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (196, '필름지', '레놀릿 _1롤', 35);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (197, '인건비', '도배', 25);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (198, '도배지', '합지벽지_평당', 3);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (199, '도배지', '실크벽지 _평당 ', 5);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (200, '인건비 ', '도장(페인트)', 30);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (201, '도장 ', '삼화페인트', 10);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (202, '도장', '노루페인트', 10);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (203, '도장', '벤자민무어_1말 = 18L', 50);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (204, '도장', '던에드워드_1말 = 18L', 70);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (205, '도장', '발페인트_10L', 160);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (206, '인건비', '마루_평당', 2.2);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (207, '마루', '구정마루_강마루_평당', 8);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (208, '마루', '구정마루_천연마루_평당', 11);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (209, '마루', '구정마루_원목마루_평당', 13);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (210, '마루', '구정마루_대리석마루_평당', 14);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (211, '마루', '이건마루_강마루_평당', 10);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (212, '마루', '이건마루_천연마루_평당', 13);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (213, '마루', '이건마루_원목마루', 17);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (214, '마루', '동화자연마루_강화마루_평당', 7);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (215, '마루', '동화자연마루_강마루_평당', 9);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (216, '마루', '동화자연마루_원목마루_평당', 16);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (217, '마루', '동화자연마루_천연대리석_평당', 40);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (218, '가구', '붙박이장', 120);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (219, '가구', '상부장', 100);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (220, '가구', '신발장', 90);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (221, '가구', '냉장고장', 120);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (222, '가구', '싱크대', 250);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (223, '인건비', '실리콘', 25);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (224, '인건비', '입주청소_평당', 1.4);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (225, '인건비', '설비', 35);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (226, '설비', '확장공사', 150);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (227, '설비', '화장실방수', 75);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (228, '도장', '탄성코트_발코니시공', 65);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (229, '행위허가', '확장신고', 55);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (230, '보양', '엘레베이터보양', 20);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (231, '동의서', '공사동의서', 30);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (232, '인터폰', '인터폰', 20);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (233, '도어락', '도어락', 40);
INSERT INTO `material_price` (`MAT_CODE`, `MAT_CAT`, `MAT_NAME`, `MAT_PRICE`) VALUES (234, '실링펜', '루씨에어', 50);
